FROM node:22-alpine

WORKDIR /app

# Node.js dev dependencies
RUN apk add --no-cache git

ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=3000

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
