FROM node:22-alpine AS builder
WORKDIR /app

# NODE_ENV must NOT be production here — npm ci skips devDependencies otherwise,
# breaking Nuxt modules (@element-plus/nuxt, @nuxt/icon, etc.) required at build time.
ENV NITRO_PRESET=node-server

COPY package*.json ./
RUN npm ci

COPY . .

ARG NUXT_PUBLIC_BROADCAST_CONNECTION
ARG NUXT_PUBLIC_REVERB_APP_ID
ARG NUXT_PUBLIC_REVERB_APP_KEY
ARG NUXT_PUBLIC_REVERB_HOST
ARG NUXT_PUBLIC_REVERB_PORT
ARG NUXT_PUBLIC_REVERB_SCHEME
ARG NUXT_PUBLIC_REVERB_PATH

ENV NUXT_PUBLIC_BROADCAST_CONNECTION=$NUXT_PUBLIC_BROADCAST_CONNECTION
ENV NUXT_PUBLIC_REVERB_APP_ID=$NUXT_PUBLIC_REVERB_APP_ID
ENV NUXT_PUBLIC_REVERB_APP_KEY=$NUXT_PUBLIC_REVERB_APP_KEY
ENV NUXT_PUBLIC_REVERB_HOST=$NUXT_PUBLIC_REVERB_HOST
ENV NUXT_PUBLIC_REVERB_PORT=$NUXT_PUBLIC_REVERB_PORT
ENV NUXT_PUBLIC_REVERB_SCHEME=$NUXT_PUBLIC_REVERB_SCHEME
ENV NUXT_PUBLIC_REVERB_PATH=$NUXT_PUBLIC_REVERB_PATH

RUN npm run build

FROM node:22-alpine
WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=3000

COPY --from=builder /app/.output ./.output

RUN addgroup -S appgroup && adduser -S appuser -G appgroup \
    && chown -R appuser:appgroup /app/.output

USER appuser

EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]
