export enum CategoryFilter {
    ALL = 'all dishes',
    MOST_POPULAR = 'most popular',
    PORK = 'pork',
    FISH = 'fish',
    BEEF = 'beef',
    VEGAN = 'vegan',
    CHICKEN = 'chicken',
    MEXICAN = 'mexican',
    JAPANESE = 'japanese',
    CHINESE = 'chinese',
    THAI = 'thai',
    KOREAN = 'korean',
    ITALIAN = 'italian',
    AMERICAN = 'american',
    VEGETARIAN = 'vegetarian',
    SEAFOOD = 'seafood',
    SIDES = 'sides',
    DESSERT = 'dessert',
    BEST = 'best',
    NEW = 'new',
    STAFF_CHOICE = 'staff choice',
    PROMOS = 'promos',
    MEATS = 'meats',
    SIDES_BANCHAN = 'sides (banchan)',
    A_LA_CARTE = 'a la carte',
    DESSERTS = 'desserts',
    BEVERAGE = 'beverage',
}


export enum OrderStatus {
    PENDING = 'pending',
    IN_PROGRESS = 'in progress',
    COMPLETE = 'completed',
    CANCELLED = 'cancelled',
    CONFIRMED = 'confirmed',
    READY = 'ready',
    SERVED = 'served',
    VOIDED = 'voided',
}
